### ISSUE TITLE
Unable to find RoomBackup imports

### ISSUE THREAD

**Issue by Suyash171** [rafi0101/Android-Room-Database-Backup#11]
After update to beta version for JAVA unable to find RoomBackup

**Comment by rafi0101** [comment]
Hello @Suyash171,
I can reproduce the problem and will look at it in the next few days

**Comment by rafi0101** [comment]
Now I am struggling a bit. I have tried a lot but I don't know how to solve the problem.

This is a version that should work but doesn't and I don't know why. Maybe it's too easy for me to find the solution.
https://github.com/rafi0101/Android-Room-Database-Backup/tree/2e9bc16b25e81189bb0d08e8b4a97c6bae305b05
https://jitpack.io/com/github/rafi0101/Android-Room-Database-Backup/2e9bc16b25/ (you can use `2e9bc16b25` as version number) (you can try but for me it did not work)

Maybe somone else knows how to fix...

**Comment by rafi0101** [comment]
Finally I found the problem: https://github.com/rafi0101/Android-Room-Database-Backup/commit/70fecf8e1a4b89be03d2ca9a4150849169990d3c
This is fixed with the next release: `v1.0.0-beta09` I'll create in the next few minues.
See: [Changelog](../blob/master/CHANGELOG.md)
