### ISSUE TITLE
1.0.0-beta11 issue

### ISSUE THREAD

**Issue by Tiemichael** [rafi0101/Android-Room-Database-Backup#22]
Hi,
first let me thank you for providing this helpful library.
I have been using V1.0.0-beta10 for a couple pf months without an issue, and upgraded to the new 1.0.0-beta11 3days ago.
When restoring the room database I now have to restart the app to see the restored data in my app.
Going back to V1.0.0-beta10 resolved the issue.

My implementation of "Android-Room-Database-Backup' is done according to the examples given here (kotlin fragment)

Thanks

**Comment by rafi0101** [comment]
Hi @Tiemichael,
okay that's interesting, because actually you always have to restart the app after a backup or restore. Because the database instance is closed in the background and (only) by a restart a new instance can be opened.

**Comment by Tiemichael** [comment]
Thanks for your reply @rafi0101 
As mentioned I always saw the restored data appear immediately with the older version.
(I need to check why my app is showing the data even without restarting the app)
Thanks!

**Comment by rafi0101** [comment]
Okay, yes check this and give feedback

**Comment by rafi0101** [comment]
I will close this issue due to inactivity. Feel free to reopen if you have any news/questions!
