### ISSUE TITLE
Reduce JDK version to 11

### ISSUE THREAD

**Issue by wangjianxiang** [rafi0101/Android-Room-Database-Backup#30]
My project is using jdk11. If I lower the version of jdk to 11, what code do I need to change
thanks

**Comment by rafi0101** [comment]
Android 14 requires jdk 17, so I won't downgrade anymore. If you want to see what I have changed please have a look at this commit: https://github.com/rafi0101/Android-Room-Database-Backup/commit/2b577c67f612c109b4a1f324346b62fa8b1e0247
