### ISSUE TITLE
Wrong backup parameters 

### ISSUE THREAD

**Issue by jjewuz** [rafi0101/Android-Room-Database-Backup#31]
**Describe the bug**
I have to different options for backup database: 1. not encrypted and user choose path
2. encrypted, with custom name and saves internally
Function do it with check special boolean. So if I first do backup in encrypted state (2), all okay. But if i after that do (1) backup option, backup allow me select path, but do it with encrypted state and with custom name. After app restart everything is ok.

**To Reproduce**
1. Do backup with next parameters: encrypted, custom password, internal path, custom name
2. after that try do do backup with; not encrypted, custom_dialog.
3. You will see that db file will be encrypted and with custom name, but you can choose path to save.

**Expected behavior**
Do backup with given parameters, save file without encryption and other extra parameters 

**Smartphone (please complete the following information):**
 - Device: Pixel 6a
 - OS: Android 14
 - Browser Chrome
 - Version beta 12

**Comment by rafi0101** [comment]
Hi Maxim,
thank you for your feedback. 
Unfortunately, I cannot reproduce this behavior on my own. I did it as you described and tried with my sample app, but everything worked as it should.
