### ISSUE TITLE
Library uses android.permission.READ_MEDIA_IMAGES and READ_MEDIA_VIDEO unexpectedly

### ISSUE THREAD

**Issue by mnkhouri** [rafi0101/Android-Room-Database-Backup#40]
**Describe the bug**
When using this library, the Play Console states: 
> Your app uses the following undeclared photo and video permissions:
> android.permission.READ_MEDIA_IMAGES
> android.permission.READ_MEDIA_VIDEO

**To Reproduce**
1. Check play console when using the app

**Expected behavior**
These permissions should not be used

**Screenshots**
<img width="1000" alt="image" src="https://github.com/user-attachments/assets/d76b97c9-1975-4ae9-bd81-f68b3c33d858">

**Comment by rafi0101** [comment]
thank you, I will have a look at that

**Comment by mnkhouri** [comment]
Google has now set a "compliance deadline" of October 31 for apps that use these permissions to either make a declaration about them, or remove the manifest permissions:

<details>
<summary>screenshot here</summary>
<img width="971" alt="image" src="https://github.com/user-attachments/assets/1a80183a-970a-44c4-a411-823f2d795693">
</details>

I hope to take a look at the code this weekend, and hopefully find some suggestions (or in the best case a PR) for which changes could be made

**Comment by mnkhouri** [comment]
I did some experimentation, and I found that these permissions are not necessary. 

I modified the following lines https://github.com/rafi0101/Android-Room-Database-Backup/blob/5efc7df91f46c9f4a8019a77fef73c83352ef64d/core/src/main/java/de/raphaelebner/roomdatabasebackup/core/RoomBackup.kt#L363-L364

to instead just be: `permissionRequestLauncher.launch(arrayOf())`, and I found this worked for both backup and restore

**Comment by rafi0101** [comment]
sorry for the very late reply. I fixed this issue and created a new release: [v1.0.2](https://github.com/rafi0101/Android-Room-Database-Backup/releases/tag/v1.0.2)

**Comment by mnkhouri** [comment]
Thank you!

**Comment by victory316** [comment]
I've came up here for investigating same issue, btw thank you for the library! I really appreciate it.
